[project]
name = "plural"
version = "2.0.0"
description = "/plu/ral"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aiohappyeyeballs==2.4.3",
    "aiohttp==3.11.2",
    "aiosignal==1.3.1",
    "annotated-types==0.7.0",
    "anyio==4.6.2.post1",
    "asgiref==3.8.1",
    "attrs==24.2.0",
    "bcrypt==4.2.0",
    "beanie==1.27.0",
    "certifi==2024.8.30",
    "cffi==1.17.1",
    "charset-normalizer==3.4.0",
    "click==8.1.7",
    "deprecated==1.2.15",
    "dnspython==2.7.0",
    "email-validator==2.2.0",
    "executing==2.1.0",
    "fastapi-cli==0.0.5",
    "fastapi==0.115.5",
    "frozenlist==1.5.0",
    "googleapis-common-protos==1.66.0",
    "h11==0.14.0",
    "httpcore==1.0.7",
    "httptools==0.6.4",
    "httpx==0.27.2",
    "idna==3.10",
    "importlib-metadata==8.5.0",
    "jinja2==3.1.4",
    "lazy-model==0.2.0",
    "logfire==2.3.0",
    "markdown-it-py==3.0.0",
    "markupsafe==3.0.2",
    "mdurl==0.1.2",
    "motor==3.6.0",
    "multidict==6.1.0",
    "opentelemetry-api==1.28.1",
    "opentelemetry-exporter-otlp-proto-common==1.28.1",
    "opentelemetry-exporter-otlp-proto-http==1.28.1",
    "opentelemetry-instrumentation==0.49b1",
    "opentelemetry-instrumentation-aiohttp-client==0.49b1",
    "opentelemetry-instrumentation-asgi==0.49b1",
    "opentelemetry-instrumentation-fastapi==0.49b1",
    "opentelemetry-instrumentation-pymongo==0.49b1",
    "opentelemetry-instrumentation-system-metrics==0.49b1",
    "opentelemetry-proto==1.28.1",
    "opentelemetry-sdk==1.28.1",
    "opentelemetry-semantic-conventions==0.49b1",
    "opentelemetry-util-http==0.49b1",
    "orjson==3.10.11",
    "packaging==24.2",
    "pillow==11.0.0",
    "propcache==0.2.0",
    "protobuf==5.28.3",
    "psutil==6.1.0",
    "pycparser==2.22",
    "pydantic==2.9.2",
    "pydantic-core==2.23.4",
    "pygments==2.18.0",
    "pymongo==4.9.2",
    "pynacl==1.5.0",
    "python-dotenv==1.0.1",
    "python-multipart==0.0.17",
    "pyyaml==6.0.2",
    "rapidfuzz==3.10.1",
    "regex==2024.11.6",
    "requests==2.32.3",
    "rich==13.9.4",
    "shellingham==1.5.4",
    "sniffio==1.3.1",
    "starlette==0.41.2",
    "thefuzz==0.22.1",
    "toml==0.10.2",
    "typer==0.13.0",
    "typing-extensions==4.12.2",
    "urllib3==2.2.3",
    "uvicorn==0.32.0",
    "uvloop==0.21.0",
    "watchfiles==0.24.0",
    "websockets==14.1",
    "wrapt==1.16.0",
    "yarl==1.17.1",
    "zipp==3.21.0",
]


[tool.mypy]
enable_incomplete_feature = ["NewGenericSyntax"]
