[package]
name = "gateway"
version = "0.1.0"
edition = "2021"

[dependencies]
fred = { version = "10.0", default-features = false, features = ["i-scripts", "enable-rustls"] }
futures = "0.3"
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1", features = ["rt", "net"] }
toml = "0.8"
twilight-gateway = { version = "0.15", default-features = false, features = ["rustls-native-roots", "twilight-http", "zlib-simd"] }
twilight-http = { version = "0.15", default-features = false, features = ["rustls-native-roots", "simd-json"] }


[build]
rustflags = ["-C", "target-cpu=native"] 