// Generated by Wrangler
// After adding bindings to `wrangler.toml`, regenerate this interface via `npm run cf-typegen`
interface Env {
    CLOUDFLARE_ZONE_ID: string
    CLOUDFLARE_API_TOKEN: string
    S3_URL: string
    S3_REGION: string
    S3_ACCESS_KEY_ID: string
    S3_BUCKET: string
    S3_SECRET_ACCESS_KEY: string
    API_URL: string
    UPLOAD_TOKEN: string
}
