// Generated by Wrangler
// After adding bindings to `wrangler.toml`, regenerate this interface via `npm run cf-typegen`
interface Env {
    S3_URL: string
    S3_ACCESS_KEY_ID: string
    S3_SECRET_ACCESS_KEY: string
    API_TOKEN: string
    UPSTASH_URL: string
    UPSTASH_TOKEN: string
}
