from enum import Enum, StrEnum, IntFlag

__all__ = (
    'GatewayOpCode',
    'GatewayEventName',
    'ReactionType',
    'GuildMemberFlags',
    'PremiumType',
    'UserFlags',
    'ChannelType',
    'MessageType',
    'MessageReferenceType',
    'MessageFlags'
)


class GatewayOpCode(Enum):
    DISPATCH = 0  # Receive
    HEARTBEAT = 1  # Send/Receive
    IDENTIFY = 2  # Send
    PRESENCE_UPDATE = 3  # Send
    VOICE_STATE_UPDATE = 4  # Send
    RESUME = 6  # Send
    RECONNECT = 7  # Receive
    REQUEST_GUILD_MEMBERS = 8  # Send
    INVALID_SESSION = 9  # Receive
    HELLO = 10  # Receive
    HEARTBEAT_ACK = 11  # Receive
    REQUEST_SOUNDBOARD_SOUNDS = 31  # Send


class GatewayEventName(StrEnum):
    IDENTIFY = 'IDENTIFY'
    RESUME = 'RESUME'
    HEARTBEAT = 'HEARTBEAT'
    REQUEST_GUILD_MEMBERS = 'REQUEST_GUILD_MEMBERS'
    REQUEST_SOUNDBOARD_SOUNDS = 'REQUEST_SOUNDBOARD_SOUNDS'
    UPDATE_VOICE_STATE = 'UPDATE_VOICE_STATE'
    UPDATE_PRESENCE = 'UPDATE_PRESENCE'
    HELLO = 'HELLO'
    READY = 'READY'
    RESUMED = 'RESUMED'
    RECONNECT = 'RECONNECT'
    INVALID_SESSION = 'INVALID_SESSION'
    APPLICATION_COMMAND_PERMISSIONS_UPDATE = 'APPLICATION_COMMAND_PERMISSIONS_UPDATE'
    AUTO_MODERATION_RULE_CREATE = 'AUTO_MODERATION_RULE_CREATE'
    AUTO_MODERATION_RULE_UPDATE = 'AUTO_MODERATION_RULE_UPDATE'
    AUTO_MODERATION_RULE_DELETE = 'AUTO_MODERATION_RULE_DELETE'
    AUTO_MODERATION_RULE_EXECUTION = 'AUTO_MODERATION_RULE_EXECUTION'
    CHANNEL_CREATE = 'CHANNEL_CREATE'
    CHANNEL_UPDATE = 'CHANNEL_UPDATE'
    CHANNEL_DELETE = 'CHANNEL_DELETE'
    CHANNEL_PINS_UPDATE = 'CHANNEL_PINS_UPDATE'
    THREAD_CREATE = 'THREAD_CREATE'
    THREAD_UPDATE = 'THREAD_UPDATE'
    THREAD_DELETE = 'THREAD_DELETE'
    THREAD_LIST_SYNC = 'THREAD_LIST_SYNC'
    THREAD_MEMBER_UPDATE = 'THREAD_MEMBER_UPDATE'
    THREAD_MEMBERS_UPDATE = 'THREAD_MEMBERS_UPDATE'
    ENTITLEMENT_CREATE = 'ENTITLEMENT_CREATE'
    ENTITLEMENT_UPDATE = 'ENTITLEMENT_UPDATE'
    ENTITLEMENT_DELETE = 'ENTITLEMENT_DELETE'
    GUILD_CREATE = 'GUILD_CREATE'
    GUILD_UPDATE = 'GUILD_UPDATE'
    GUILD_DELETE = 'GUILD_DELETE'
    GUILD_AUDIT_LOG_ENTRY_CREATE = 'GUILD_AUDIT_LOG_ENTRY_CREATE'
    GUILD_BAN_ADD = 'GUILD_BAN_ADD'
    GUILD_BAN_REMOVE = 'GUILD_BAN_REMOVE'
    GUILD_EMOJIS_UPDATE = 'GUILD_EMOJIS_UPDATE'
    GUILD_STICKERS_UPDATE = 'GUILD_STICKERS_UPDATE'
    GUILD_INTEGRATIONS_UPDATE = 'GUILD_INTEGRATIONS_UPDATE'
    GUILD_MEMBER_ADD = 'GUILD_MEMBER_ADD'
    GUILD_MEMBER_REMOVE = 'GUILD_MEMBER_REMOVE'
    GUILD_MEMBER_UPDATE = 'GUILD_MEMBER_UPDATE'
    GUILD_MEMBERS_CHUNK = 'GUILD_MEMBERS_CHUNK'
    GUILD_ROLE_CREATE = 'GUILD_ROLE_CREATE'
    GUILD_ROLE_UPDATE = 'GUILD_ROLE_UPDATE'
    GUILD_ROLE_DELETE = 'GUILD_ROLE_DELETE'
    GUILD_SCHEDULED_EVENT_CREATE = 'GUILD_SCHEDULED_EVENT_CREATE'
    GUILD_SCHEDULED_EVENT_UPDATE = 'GUILD_SCHEDULED_EVENT_UPDATE'
    GUILD_SCHEDULED_EVENT_DELETE = 'GUILD_SCHEDULED_EVENT_DELETE'
    GUILD_SCHEDULED_EVENT_USER_ADD = 'GUILD_SCHEDULED_EVENT_USER_ADD'
    GUILD_SCHEDULED_EVENT_USER_REMOVE = 'GUILD_SCHEDULED_EVENT_USER_REMOVE'
    GUILD_SOUNDBOARD_SOUND_CREATE = 'GUILD_SOUNDBOARD_SOUND_CREATE'
    GUILD_SOUNDBOARD_SOUND_UPDATE = 'GUILD_SOUNDBOARD_SOUND_UPDATE'
    GUILD_SOUNDBOARD_SOUND_DELETE = 'GUILD_SOUNDBOARD_SOUND_DELETE'
    GUILD_SOUNDBOARD_SOUNDS_UPDATE = 'GUILD_SOUNDBOARD_SOUNDS_UPDATE'
    SOUNDBOARD_SOUNDS = 'SOUNDBOARD_SOUNDS'
    INTEGRATION_CREATE = 'INTEGRATION_CREATE'
    INTEGRATION_UPDATE = 'INTEGRATION_UPDATE'
    INTEGRATION_DELETE = 'INTEGRATION_DELETE'
    INTERACTION_CREATE = 'INTERACTION_CREATE'
    INVITE_CREATE = 'INVITE_CREATE'
    INVITE_DELETE = 'INVITE_DELETE'
    MESSAGE_CREATE = 'MESSAGE_CREATE'
    MESSAGE_UPDATE = 'MESSAGE_UPDATE'
    MESSAGE_DELETE = 'MESSAGE_DELETE'
    MESSAGE_DELETE_BULK = 'MESSAGE_DELETE_BULK'
    MESSAGE_REACTION_ADD = 'MESSAGE_REACTION_ADD'
    MESSAGE_REACTION_REMOVE = 'MESSAGE_REACTION_REMOVE'
    MESSAGE_REACTION_REMOVE_ALL = 'MESSAGE_REACTION_REMOVE_ALL'
    MESSAGE_REACTION_REMOVE_EMOJI = 'MESSAGE_REACTION_REMOVE_EMOJI'
    PRESENCE_UPDATE = 'PRESENCE_UPDATE'
    STAGE_INSTANCE_CREATE = 'STAGE_INSTANCE_CREATE'
    STAGE_INSTANCE_UPDATE = 'STAGE_INSTANCE_UPDATE'
    STAGE_INSTANCE_DELETE = 'STAGE_INSTANCE_DELETE'
    SUBSCRIPTION_CREATE = 'SUBSCRIPTION_CREATE'
    SUBSCRIPTION_UPDATE = 'SUBSCRIPTION_UPDATE'
    SUBSCRIPTION_DELETE = 'SUBSCRIPTION_DELETE'
    TYPING_START = 'TYPING_START'
    USER_UPDATE = 'USER_UPDATE'
    VOICE_CHANNEL_EFFECT_SEND = 'VOICE_CHANNEL_EFFECT_SEND'
    VOICE_STATE_UPDATE = 'VOICE_STATE_UPDATE'
    VOICE_SERVER_UPDATE = 'VOICE_SERVER_UPDATE'
    WEBHOOKS_UPDATE = 'WEBHOOKS_UPDATE'
    MESSAGE_POLL_VOTE_ADD = 'MESSAGE_POLL_VOTE_ADD'
    MESSAGE_POLL_VOTE_REMOVE = 'MESSAGE_POLL_VOTE_REMOVE'


class ReactionType(Enum):
    NORMAL = 0
    BURST = 1


class GuildMemberFlags(IntFlag):
    DID_REJOIN = 1 << 0
    COMPLETED_ONBOARDING = 1 << 1
    BYPASSES_VERIFICATION = 1 << 2
    STARTED_ONBOARDING = 1 << 3
    IS_GUEST = 1 << 4
    STARTED_HOME_ACTIONS = 1 << 5
    COMPLETED_HOME_ACTIONS = 1 << 6
    AUTOMOD_QUARANTINED_USERNAME = 1 << 7
    DM_SETTINGS_UPSELL_ACKNOWLEDGED = 1 << 9


class PremiumType(Enum):
    NONE = 0
    NITRO_CLASSIC = 1
    NITRO = 2
    NITRO_BASIC = 3


class UserFlags(IntFlag):
    STAFF = 1 << 0
    PARTNER = 1 << 1
    HYPESQUAD = 1 << 2
    BUG_HUNTER_LEVEL_1 = 1 << 3
    HYPESQUAD_ONLINE_HOUSE_1 = 1 << 6
    HYPESQUAD_ONLINE_HOUSE_2 = 1 << 7
    HYPESQUAD_ONLINE_HOUSE_3 = 1 << 8
    PREMIUM_EARLY_SUPPORTER = 1 << 9
    TEAM_PSEUDO_USER = 1 << 10
    BUG_HUNTER_LEVEL_2 = 1 << 14
    VERIFIED_BOT = 1 << 16
    VERIFIED_DEVELOPER = 1 << 17
    CERTIFIED_MODERATOR = 1 << 18
    BOT_HTTP_INTERACTIONS = 1 << 19
    ACTIVE_DEVELOPER = 1 << 22


class ChannelType(Enum):
    GUILD_TEXT = 0
    DM = 1
    GUILD_VOICE = 2
    GROUP_DM = 3
    GUILD_CATEGORY = 4
    GUILD_ANNOUNCEMENT = 5
    ANNOUNCEMENT_THREAD = 10
    PUBLIC_THREAD = 11
    PRIVATE_THREAD = 12
    GUILD_STAGE_VOICE = 13
    GUILD_DIRECTORY = 14
    GUILD_FORUM = 15
    GUILD_MEDIA = 16


class MessageType(Enum):
    DEFAULT = 0
    RECIPIENT_ADD = 1
    RECIPIENT_REMOVE = 2
    CALL = 3
    CHANNEL_NAME_CHANGE = 4
    CHANNEL_ICON_CHANGE = 5
    CHANNEL_PINNED_MESSAGE = 6
    USER_JOIN = 7
    GUILD_BOOST = 8
    GUILD_BOOST_TIER_1 = 9
    GUILD_BOOST_TIER_2 = 10
    GUILD_BOOST_TIER_3 = 11
    CHANNEL_FOLLOW_ADD = 12
    GUILD_DISCOVERY_DISQUALIFIED = 14
    GUILD_DISCOVERY_REQUALIFIED = 15
    GUILD_DISCOVERY_GRACE_PERIOD_INITIAL_WARNING = 16
    GUILD_DISCOVERY_GRACE_PERIOD_FINAL_WARNING = 17
    THREAD_CREATED = 18
    REPLY = 19
    CHAT_INPUT_COMMAND = 20
    THREAD_STARTER_MESSAGE = 21
    GUILD_INVITE_REMINDER = 22
    CONTEXT_MENU_COMMAND = 23
    AUTO_MODERATION_ACTION = 24
    ROLE_SUBSCRIPTION_PURCHASE = 25
    INTERACTION_PREMIUM_UPSELL = 26
    STAGE_START = 27
    STAGE_END = 28
    STAGE_SPEAKER = 29
    STAGE_TOPIC = 31
    GUILD_APPLICATION_PREMIUM_SUBSCRIPTION = 32
    GUILD_INCIDENT_ALERT_MODE_ENABLED = 36
    GUILD_INCIDENT_ALERT_MODE_DISABLED = 37
    GUILD_INCIDENT_REPORT_RAID = 38
    GUILD_INCIDENT_REPORT_FALSE_ALARM = 39
    PURCHASE_NOTIFICATION = 44
    POLL_RESULT = 46


class MessageReferenceType(Enum):
    DEFAULT = 0
    FORWARD = 1


class MessageFlags(IntFlag):
    CROSSPOSTED = 1 << 0
    IS_CROSSPOST = 1 << 1
    SUPPRESS_EMBEDS = 1 << 2
    SOURCE_MESSAGE_DELETED = 1 << 3
    URGENT = 1 << 4
    HAS_THREAD = 1 << 5
    EPHEMERAL = 1 << 6
    LOADING = 1 << 7
    FAILED_TO_MENTION_SOME_ROLES_IN_THREAD = 1 << 8
    SUPPRESS_NOTIFICATIONS = 1 << 12
    IS_VOICE_MESSAGE = 1 << 13
